spring:
  application:
    name: recommender-engine

  datasource:
    url: jdbc:postgresql://db:5432/recommender_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # CREDENCIALES PARA DESARROLLO - OJO!
  security:
    user:
      name: admin
      password: password
      roles: ADMIN,PLAYER

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: mySuperSecretKeyThatIsAtLeast32CharsLong!
  expiration-ms: 86400000

logging:
  level:
    com.codebytes2.recommender: DEBUG
    org.springframework.security: DEBUG